### ISSUE TITLE
missing license

### ISSUE THREAD

**Issue by fleck** [Acidic9/tailwind-classes-sorter#1]
Would you be able to add a license to this package?

**Comment by tqwewe** [comment]
@fleck interesting concern 🤔 
I've added the license now :)

**Comment by fleck** [comment]
thanks! just unsure about using an unlicensed package, not sure what the ramifications of that are ¯\_(ツ)_/¯. Ran an audit and this was the only package out of thousands in a project I'm working on without one, anyway, thanks for the quick turnaround!

**Comment by tqwewe** [comment]
No problem, do you need me to push this to NPM as a new version @fleck ?

**Comment by fleck** [comment]
If you can cut a new version on NPM that'd be awesome, will help my OCD when running a license check!

**Comment by tqwewe** [comment]
@fleck all done (v1.0.11)! Your terminal will be looking after running a license check from now on I hope!
