### ISSUE TITLE
Vue.js / Nuxt.js example

### ISSUE THREAD

**Issue by davision** [Acidic9/tailwind-classes-sorter#2]
Is there any example of how to integrate this plugin into a Vue or Nuxt project? Iw ould love to use your solution here.

**Comment by aniforprez** [comment]
Vue or Nuxt should work the same as HTML if you're using HTML templates right? If you use the prettier plugin it should just work I think

**Comment by tqwewe** [comment]
I think so @aniforprez , thanks for adding this.. I don't use Vue these days so I haven't tested it yet.

**Comment by aniforprez** [comment]
Yeah haven't tested it myself but I'm hoping it would just work. Appreciate the effort put into this package!
